### ISSUE TITLE
Error Creating step

### ISSUE THREAD

**Issue by joergbirkhold** [bitrise-io/bitrise-plugins-step#27]
I do get the followeing Error when I try to create a step:

ERROR: Failed to write template into file: Failed to evaluate template: Failed to find templates dir/box: could not locate box "templates"

MacOS 10.14.4
Version 0.9.9

**Comment by bitce** [comment]
Hi @joergbirkhold,

Thanks for your report! We're investigating the issue, will keep you updated!

**Comment by alexanderwe** [comment]
I am also seeing this error on: 

Bitrise CLI: 1.47.0
Step plugin: 0.9.11
macOS: 11.3.1

**Comment by Roland-Bak** [comment]
Hey there @alexanderwe 👋

Could you please send us a screencast of your process when encountering this issue to https://support.bitrise.io/hc? We'd be happy to look into this 🙂

**Comment by alexanderwe** [comment]
@Roland-Bak Sure I can do that ! Is there a specific place where I can post this ? Did you mean I should post it into the discussions ?

**Comment by mateherber** [comment]
Hi @alexanderwe, We released the `0.10.1` version of the step plugin which should solve this issue. Can you please verify?

**Comment by alexanderwe** [comment]
@mateherber `0.10.1` fixes the issue. Creating a step works like a charm now. Thanks for fixing !

**Comment by mateherber** [comment]
Thank you, I'm gonna close this issue then!
